### ISSUE TITLE
RTL-SDR instructions too brief

### ISSUE THREAD

**Issue by micsthepick** [ryanvolz/radioconda#111]
The RTL-SDR blog page includes the manufacturer and device id for the SDR, and for my case I needed to verify that, as 
![image](https://github.com/user-attachments/assets/8bcd1f17-0402-4fe4-9216-9e387606c669)
in this image, my rtl-sdr was the second (Bulk in interface-1) entry.

**Comment by ryanvolz** [comment]
How about changing the text from

> [Install the WinUSB driver with Zadig](https://github.com/ryanvolz/radioconda?tab=readme-ov-file#installing-the-winusb-driver-with-zadig), selecting the device that is called "Bulk-In, Interface (Interface 0)".

to

> [Install the WinUSB driver with Zadig](https://github.com/ryanvolz/radioconda?tab=readme-ov-file#installing-the-winusb-driver-with-zadig), selecting the device that is called "Bulk-In, Interface" and verifying the manufacturer and device ID if there are multiple options.

?

**Comment by micsthepick** [comment]
Never mind, it was seemingly working but I needed to actually follow
the instructions verbatim, and thus had to do the signalseverywhere USB
error -12 fix

You may close this issue
