### ISSUE TITLE
python 3.10?

### ISSUE THREAD

**Issue by cessna85** [ryanvolz/radioconda#17]
Are there any plans to update python to 3.10.x?

**Comment by ryanvolz** [comment]
Yeah, I can change it for the next release. The only thing keeping it at Python 3.8 is compatibility with Windows 7 (other platforms are already at Python 3.10), and there probably aren't enough Windows 7 users to justify that.

Just curious: what features from Python 3.10 are you wanting to have?

**Comment by cessna85** [comment]
Ahhh... That makes sense.
I am looking to use the new [pattern matching syntax](https://peps.python.org/pep-0636/) 
I was able to upgrade to python to 3.10 using radioconda's environment without any issues so it just made me curious to if there was a particular package that had issues with 3.10.

**Comment by ryanvolz** [comment]
Released in 2022.04.15
