### ISSUE TITLE
After install the radioconda, I can't open the GNUradio

### ISSUE THREAD

**Issue by blaticslm** [ryanvolz/radioconda#18]
When finish the installation, I click the GNUradio icon, and the cmd window shows up for less than a second and then disappears. How to solve this issue? 

![图片](https://user-images.githubusercontent.com/47236078/162330290-2828669d-cb04-4bc4-b7b5-e2d227b9e829.png)

The picture above is showing the crash. 

Really thanks for your response!

**Comment by ryanvolz** [comment]
I don't see anything in your screenshot, but I can conclude from the description that GRC is crashing when you launch it. In order to get more information about what's causing the crash, try the following:

1. Launch the "Conda Prompt" from the Start menu.
2. Run the command `gnuradio-config-info --print-all` and post the output here.
3. Run the command `gnuradio-companion` (expecting it will crash) and post the output here.

**Comment by blaticslm** [comment]
> I don't see anything in your screenshot, but I can conclude from the description that GRC is crashing when you launch it. In order to get more information about what's causing the crash, try the following:
> 
>     1. Launch the "Conda Prompt" from the Start menu.
> 
>     2. Run the command `gnuradio-config-info --print-all` and post the output here.
> 
>     3. Run the command `gnuradio-companion` (expecting it will crash) and post the output here.

I think I made it! I forget to set up the conda environment for gnuradio. Now it works.

**Comment by ryanvolz** [comment]
Great!

**Comment by reverseideol0gy** [comment]
> > I don't see anything in your screenshot, but I can conclude from the description that GRC is crashing when you launch it. In order to get more information about what's causing the crash, try the following:
> > ```
> > 1. Launch the "Conda Prompt" from the Start menu.
> > 
> > 2. Run the command `gnuradio-config-info --print-all` and post the output here.
> > 
> > 3. Run the command `gnuradio-companion` (expecting it will crash) and post the output here.
> > ```
> 
> I think I made it! I forget to set up the conda environment for gnuradio. Now it works.

i can't run conda Prompt too 
![ภาพ](https://user-images.githubusercontent.com/95678919/167287425-480ee2b0-f0c0-4691-bd8a-578fdc9b1f36.png)

้how to set conda environment for gnuradio can you share how to fix for me i have this problem too.

**Comment by blaticslm** [comment]
https://wiki.gnuradio.org/index.php/CondaInstall#Installation_using_conda

I think you just need to uninstall the one you have and delete all its relevant files. Then you can follow the steps from the above website. I redo it and eventually works for me.

**Comment by ryanvolz** [comment]
@reverseideol0gy You have Python 2.7 installed in `C:\\Python27` and that is clobbering everything the conda installation is trying to do. I don't know why that's happening, but surely you could fix it by uninstalling that other version of Python. If that's not possible, then maybe reinstalling radioconda and choosing to set it as your system Python would override the other installation, but that might be futile.
