### ISSUE TITLE
Upgr

### ISSUE THREAD

**Issue by MountainLogic** [ryanvolz/radioconda#2]
I did have radiconda working uder win10, but I just did a mamba upgrade all and now when I go to start/Gnu Radio Companion (Radioconda) App, I have a common box pop-up ever so briefly, then it goes away.  The Radioconda command line has no path to find gnuradaio-companion.  Not sure what my next stops would be.   BTW, also looking to use IIO on win10.

**Comment by ryanvolz** [comment]
That may have upgraded you to GR 3.9, which could be the issue since it hasn't had much end user testing, especially on Windows.

Can you open a Conda prompt and post the output of `mamba list`? That will tell us what is still actually installed. It's curious that you can't even run GRC from the command line, which is something I would normally recommend for figuring out weird launch issues.

**Comment by ryanvolz** [comment]
Oh and I forgot to respond to the IIO part. `iio` should work as far as I know, but do you mean `gr-iio` for the GNU Radio blocks? For that, I haven't been able to add it to conda-forge because upstream hasn't made an official release that was compatible with GR 3.8 or 3.9. As you may know though, it's in the process of being included into the main GR repository, so I'm hopeful to be able to have it available for GR 3.9 before too long.

**Comment by MountainLogic** [comment]
I saw some promises about gr-iio being included in 3.9, oh well, Analog Devices....

BTW, I'm usually also on gr chat.



`
mamba list                                                                                                                                                                                                                               __    __    __    __                                                                                                   /  \  /  \  /  \  /  \                                                                                                 /    \/    \/    \/    \                                                                                ███████████████/  /██/  /██/  /██/  /████████████████████████                                                                         /  / \   / \   / \   / \  \____                                                                                        /  /   \_/   \_/   \_/   \    o \__,                                                                                   / _/                       \_____/  `                                                                                   |/                                                                                                                  ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗                                                                           ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗                                                                          ██╔████╔██║███████║██╔████╔██║██████╔╝███████║                                                                          ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║                                                                          ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║                                                                          ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝                                                                                                                                                                                                  mamba (0.10.0) supported by @QuantStack                                                                                                                                                                                                         GitHub:  https://github.com/mamba-org/mamba                                                                             Twitter: https://twitter.com/QuantStack                                                                                                                                                                                                 █████████████████████████████████████████████████████████████                                                                                                                                                                                   # packages in environment at C:\Users\selliott\radioconda:                                                              #                                                                                                                       # Name                    Version                   Build  Channel                                                      adwaita-icon-theme        3.38.0               heaa5689_1    conda-forge                                                appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge                                                argh                      0.26.2                py38_1001    conda-forge                                                atk-1.0                   2.36.0               h7222f49_4    conda-forge                                                backcall                  0.2.0              pyh9f0ad1d_0    conda-forge                                                backports                 1.0                        py_2    conda-forge                                                backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge                                            boost-cpp                 1.74.0               h54f0996_2    conda-forge                                                brotlipy                  0.7.0           py38hab1e662_1001    conda-forge                                              bzip2                     1.0.8                h8ffe710_4    conda-forge                                                ca-certificates           2020.12.5            h5b45459_0    conda-forge                                                cached-property           1.5.2                hd8ed1ab_1    conda-forge                                                cached_property           1.5.2              pyha770c72_1    conda-forge                                                cairo                     1.16.0            hb19e0ff_1008    conda-forge                                                certifi                   2020.12.5        py38haa244fe_1    conda-forge                                                cffi                      1.14.5           py38hd8c33c5_0    conda-forge                                                chardet                   4.0.0            py38haa244fe_1    conda-forge                                                click                     7.1.2              pyh9f0ad1d_0    conda-forge                                                click-plugins             1.1.1                      py_0    conda-forge                                                codec2                    0.9.2                h301d43c_1    conda-forge                                                colorama                  0.4.4              pyh9f0ad1d_0    conda-forge                                                conda                     4.10.1           py38haa244fe_0    conda-forge                                                conda-package-handling    1.7.3            py38h31c79cd_0    conda-forge                                                construct                 2.9.45                     py_0    conda-forge                                                cryptography              3.4.7            py38hd7da0ea_0    conda-forge                                                cycler                    0.10.0                     py_2    conda-forge                                                decorator                 5.0.7              pyhd8ed1ab_0    conda-forge                                                digital_rf                2.6.6            py38haa20497_0    conda-forge                                                epoxy                     1.5.5                h8d14728_0    conda-forge                                                expat                     2.3.0                h39d44d4_0    conda-forge                                                fftw                      3.3.9           nompi_hd3ad3c4_101    conda-forge                                             fontconfig                2.13.1            h1989441_1005    conda-forge                                                freetype                  2.10.4               h546665d_1    conda-forge                                                fribidi                   1.0.10               h62dcd97_0    conda-forge                                                fs                        2.4.11           py38h32f6830_2    conda-forge                                                gdk-pixbuf                2.42.6               h1c5aac7_0    conda-forge                                                gettext                   0.19.8.1          h1a89ca6_1005    conda-forge                                                glew                      2.1.0                h39d44d4_2    conda-forge                                                glib                      2.68.1               h0e60522_0    conda-forge                                                glib-tools                2.68.1               h0e60522_0    conda-forge                                                gnuradio                  3.9.1.0          py38h1317bc6_3    conda-forge                                                gnuradio-core             3.9.1.0          py38h76584d8_3    conda-forge                                                gnuradio-grc              3.9.1.0          py38h33e2607_3    conda-forge                                                gnuradio-osmosdr          0.2.3            py38h2f756a0_5    conda-forge                                                gnuradio-qtgui            3.9.1.0          py38h133500e_3    conda-forge                                                gnuradio-satellites       4.0.0            py38h8ca1ce4_1    conda-forge                                                gnuradio-soapy            2.1.3.1          py38hb47969d_2    conda-forge                                                gnuradio-uhd              3.9.1.0          py38h0b6410d_3    conda-forge                                                gnuradio-video-sdl        3.9.1.0          py38h33e2607_3    conda-forge                                                gnuradio-zeromq           3.9.1.0          py38h2f484db_3    conda-forge                                                gobject-introspection     1.68.0           py38hcb2c0c0_1    conda-forge                                                gqrx                      2.14.4               h3070aff_3    conda-forge                                                graphite2                 1.3.13                     1000    conda-forge                                                gsl                       2.6                  hdfb1a43_2    conda-forge                                                gtk3                      3.24.28              h9a703b0_0    conda-forge                                                h5py                      3.2.1           nompi_py38he6c2248_100    conda-forge                                         harfbuzz                  2.8.0                hc601d6f_1    conda-forge                                                hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge                                            hicolor-icon-theme        0.17                 h57928b3_2    conda-forge                                                icu                       68.1                 h0e60522_0    conda-forge                                                idna                      2.10               pyh9f0ad1d_0    conda-forge                                                intel-openmp              2021.2.0           h57928b3_616    conda-forge                                                ipython                   7.22.0           py38h43734a8_0    conda-forge                                                ipython_genutils          0.2.0                      py_1    conda-forge                                                jedi                      0.18.0           py38haa244fe_2    conda-forge                                                jpeg                      9d                   he774522_0    conda-forge                                                kiwisolver                1.3.1            py38hbd9d945_1    conda-forge                                                krb5                      1.17.2               hbae68bd_0    conda-forge                                                lcms2                     2.12                 h2a16943_0    conda-forge                                                libad9361-iio             0.2                  h3326528_1    conda-forge                                                libarchive                3.5.1                hf621db8_1    conda-forge                                                libblas                   3.9.0                     8_mkl    conda-forge                                                libcblas                  3.9.0                     8_mkl    conda-forge                                                libclang                  11.1.0          default_h5c34c98_0    conda-forge                                             libcurl                   7.76.1               hf1763fc_1    conda-forge                                                libffi                    3.3                  h0e60522_2    conda-forge                                                libflac                   1.3.3                h0e60522_1    conda-forge                                                libglib                   2.68.1               h1e62bf3_0    conda-forge                                                libiconv                  1.16                 he774522_0    conda-forge                                                libiio                    0.21             py38h292cb97_4    conda-forge                                                liblapack                 3.9.0                     8_mkl    conda-forge                                                liblimesuite              20.10.0              h0e60522_0    conda-forge                                                libm2k                    0.4.0            py38haf3f0dc_2    conda-forge                                                libogg                    1.3.4                h8ffe710_1    conda-forge                                                libopus                   1.3.1                h8ffe710_1    conda-forge                                                libpng                    1.6.37               ha81a0f5_2    conda-forge                                                librsvg                   2.50.4               h09c2f97_0    conda-forge                                                libsndfile                1.0.31               h0e60522_1    conda-forge                                                libsodium                 1.0.18               h62dcd97_1    conda-forge                                                libsolv                   0.7.18               h7755175_0    conda-forge                                                libssh2                   1.9.0                h680486a_6    conda-forge                                                libtiff                   4.2.0                hc10be44_0    conda-forge                                                libusb                    1.0.24               h0e60522_1    conda-forge                                                libvorbis                 1.3.7                ha925a31_0    conda-forge                                                libxml2                   2.9.10               hf5bbc77_4    conda-forge                                                libxslt                   1.1.33               h65864e5_2    conda-forge                                                limesuite                 20.10.0              hbaad480_0    conda-forge                                                log4cpp                   1.1.3             ha925a31_1002    conda-forge                                                lxml                      4.6.3            py38h292cb97_0    conda-forge                                                lz4-c                     1.9.3                h8ffe710_0    conda-forge                                                lzo                       2.10              hfa6e2cd_1000    conda-forge                                                m2w64-gcc-libgfortran     5.3.0                         6    conda-forge                                                m2w64-gcc-libs            5.3.0                         7    conda-forge                                                m2w64-gcc-libs-core       5.3.0                         7    conda-forge                                                m2w64-gmp                 6.1.0                         2    conda-forge                                                m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge                                             mako                      1.1.4              pyh44b312d_0    conda-forge                                                mamba                     0.10.0           py38hdd88130_0    conda-forge                                                markupsafe                1.1.1            py38h294d835_3    conda-forge                                                matplotlib-base           3.4.1            py38heae8d8c_0    conda-forge                                                menuinst                  1.4.16           py38h32f6830_1    conda-forge                                                mkl                       2020.4             hb70f87d_311    conda-forge                                                mpir                      3.0.0             he025d50_1002    conda-forge                                                msys2-conda-epoch         20160418                      1    conda-forge                                                numpy                     1.20.2           py38h09042cb_0    conda-forge                                                olefile                   0.46               pyh9f0ad1d_1    conda-forge                                                openjpeg                  2.4.0                h48faf41_0    conda-forge                                                openssl                   1.1.1k               h8ffe710_0    conda-forge                                                packaging                 20.9               pyh44b312d_0    conda-forge                                                pango                     1.48.4               hd84fcdd_0    conda-forge                                                parso                     0.8.2              pyhd8ed1ab_0    conda-forge                                                pathtools                 0.1.2                      py_1    conda-forge                                                pcre                      8.44                 ha925a31_0    conda-forge                                                pickleshare               0.7.5           py38h32f6830_1002    conda-forge                                              pillow                    8.1.2            py38h9273828_1    conda-forge                                                pip                       21.0.1             pyhd8ed1ab_0    conda-forge                                                pixman                    0.40.0               h8ffe710_0    conda-forge                                                prompt-toolkit            3.0.18             pyha770c72_0    conda-forge                                                pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge                                                pyadi-iio                 0.0.7              pyhd8ed1ab_0    conda-forge                                                pycairo                   1.20.0           py38h979ce04_1    conda-forge                                                pycosat                   0.6.3           py38h294d835_1006    conda-forge                                              pycparser                 2.20               pyh9f0ad1d_2    conda-forge                                                pygments                  2.8.1              pyhd8ed1ab_0    conda-forge                                                pygobject                 3.40.1           py38hacb06c2_1    conda-forge                                                pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge                                                pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge                                                pyqt                      5.12.3           py38haa244fe_7    conda-forge                                                pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge                                                pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge                                                pyqtchart                 5.12             py38h885f38d_7    conda-forge                                                pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge                                                pyreadline                2.1             py38haa244fe_1003    conda-forge                                              pysocks                   1.7.1            py38haa244fe_3    conda-forge                                                python                    3.8.0                hc9e8b01_5    conda-forge                                                python-dateutil           2.8.1                      py_0    conda-forge                                                python_abi                3.8                      1_cp38    conda-forge                                                pytz                      2021.1             pyhd8ed1ab_0    conda-forge                                                pywin32                   300              py38h294d835_0    conda-forge                                                pyyaml                    5.4.1            py38h294d835_0    conda-forge                                                pyzmq                     22.0.3           py38h09162b1_1    conda-forge                                                qt                        5.12.9               h5909a2a_4    conda-forge                                                qwt                       6.1.6                h552f0f6_0    conda-forge                                                radioconda_console_shortcut 1.0                           0    ryanvolz                                                 reproc                    14.2.1               h8ffe710_0    conda-forge                                                reproc-cpp                14.2.1               h0e60522_0    conda-forge                                                requests                  2.25.1             pyhd3deb0d_0    conda-forge                                                rtl-sdr                   0.6.0                h8ffe710_2    conda-forge                                                ruamel.yaml               0.16.12          py38h294d835_2    conda-forge                                                ruamel.yaml.clib          0.2.2            py38h294d835_2    conda-forge                                                ruamel_yaml               0.15.80         py38h294d835_1004    conda-forge                                              sdl                       1.2.15               h21ff451_1    conda-forge                                                setuptools                49.6.0           py38haa244fe_3    conda-forge                                                six                       1.15.0             pyh9f0ad1d_0    conda-forge                                                soapysdr                  0.7.2            py38hbd9d945_4    conda-forge                                                soapysdr-module-lms7      20.10.0              h54dde43_0    conda-forge                                                soapysdr-module-plutosdr  0.2.1                h94b6719_1    conda-forge                                                soapysdr-module-remote    0.5.2                hcf9c798_1    conda-forge                                                soapysdr-module-rtlsdr    0.3.0                h74a9793_0    conda-forge                                                soapysdr-module-uhd       0.4.1                h8f9bfca_2    conda-forge                                                sqlite                    3.35.4               h8ffe710_0    conda-forge                                                tk                        8.6.10               he774522_1    conda-forge                                                tornado                   6.1              py38h294d835_1    conda-forge                                                tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge                                                traitlets                 5.0.5                      py_0    conda-forge                                                uhd                       4.0.0.0          py38h1d4ea3b_4    conda-forge                                                urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge                                                vc                        14.2                 hb210afc_4    conda-forge                                                volk                      2.4.1            py38h885f38d_1    conda-forge                                                vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge                                                watchdog                  2.0.2            py38haa244fe_0    conda-forge                                                wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge                                                wheel                     0.36.2             pyhd3deb0d_0    conda-forge                                                win_inet_pton             1.1.0            py38haa244fe_2    conda-forge                                                wincertstore              0.2             py38haa244fe_1006    conda-forge                                              wxwidgets                 3.1.3                h8e1ed31_4    conda-forge                                                xz                        5.2.5                h62dcd97_1    conda-forge                                                yaml                      0.2.5                he774522_0    conda-forge                                                zeromq                    4.3.4                h0e60522_0    conda-forge                                                zlib                      1.2.11            h62dcd97_1010    conda-forge                                                zstd                      1.4.9                h6255e5f_0    conda-forge            

`

**Comment by ryanvolz** [comment]
It looks like everything is there. Can you see if `gnuradio-config-info` will run or turn up any issues? Can you see if `%PREFIX%\Library\bin\gnuradio-companion.exe` exists and if you can run it from there with the explicit path? (Other notable executables should also be in the same directory.)

**Comment by MountainLogic** [comment]
Was a conflict with pathos.  Once pathos was removed all seems to be better.  Think you can close this.  Details from radioconda install:

Interesting, no gnuradio-config-info seems to be preset in the path ( gnur then tab fails to show me any completion options).


```
(base) C:\Users\foobar\radioconda\Scripts>gnuradio-config-info --prefix
C:\Program Files\PothosSDR
 
```

So that reminds me that I did  install pathos, so that may be the problem. 

Interesting that gnuradio-companion.exe is not in the radoconda script directory.  Shuold three not be a few more GnuRadio bins in here? 

Inside radioconda command line I ran:
```
                                                                                                                        
Directory of C:\Users\foobar\radioconda\Scripts                                                                                                                                                                                              11/01/2019  02:30 PM            40,960 2to3.exe 
10/26/2020  08:42 AM            41,984 chardetect.exe
04/14/2021  09:40 AM           74,752 conda-env.exe                                                                    
04/14/2021  04:15 PM            74,752 conda.exe                                                                        
01/15/2021  03:04 AM            41,984 cph.exe                                                                          
02/12/2021  05:47 PM            74,752 drf.exe                                                                          
10/26/2020  08:42 AM            41,984 easy_install.exe                                                                 
01/15/2021  03:04 AM            41,984 f2py.exe                                                                        
01/15/2021  03:04 AM            41,984 gnuradio-companion.exe                                                           
01/15/2021  03:04 AM            41,984 grcc.exe                                                                         
01/15/2021  03:04 AM            41,984 gr_filter_design.exe                                                             
01/15/2021  03:04 AM            41,984 gr_modtool.exe                                                                   
11/01/2019  02:30 PM            40,960 idle.exe                                                                        
01/15/2021  03:04 AM            41,984 iptest.exe                                                                       
01/15/2021  03:04 AM            41,984 iptest3.exe                                                                      
01/15/2021  03:04 AM            41,984 ipython.exe                                                                     
01/15/2021  03:04 AM            41,984 ipython3.exe                                                                     
03/26/2021  02:20 PM            74,752 mako-render.exe                                                                 
01/15/2021  03:04 AM            41,984 mamba.exe                                                                        
09/29/2020  01:01 PM            41,984 menuinst.exe                                                                     
03/26/2021  02:20 PM            74,752 pip.exe                                                                          
03/26/2021  02:20 PM            74,752 pip3.exe                                                                         
11/01/2019  02:30 PM            40,960 pydoc.exe                                                                        
03/26/2021  02:20 PM            74,752 pygmentize.exe                                                                   
04/14/2021  04:15 PM            74,752 tqdm.exe                                                                         
01/15/2021  03:04 AM            41,984 uhd_images_downloader.exe                                                       
01/15/2021  03:04 AM            41,984 uhd_siggen.exe                                                                  
01/15/2021  03:04 AM            41,984 watchmedo.exe                                                                    
03/26/2021  02:20 PM            74,752 wheel.exe                                                                         
           29 File(s)      1,509,376 bytes                                      
              0 Dir(s)  41,682,497,536 bytes free                                                                                                                                                                                              (base) C:\Users\foobar\radioconda\Scripts>gnuradio-companion.exe                                                      
Traceback (most recent call last):                                                                                        
File "C:\Users\foobar\radioconda\Scripts\gnuradio-companion-script.py", line 10, in <module>                       
     sys.exit(main())                                                                                                      
File "C:\Users\foobar\radioconda\lib\site-packages\gnuradio\grc\main.py", line 72, in main                              platform.build_library()                                                                                              
File "C:\Users\foobar\radioconda\lib\site-packages\gnuradio\grc\core\platform.py", line 192, in build_library raise RuntimeError(errstr)                                                                                          
RuntimeError: Failed to find built-in GRC blocks (specifically, the 'options' block). Ensure your GRC block paths are correct and at least one points to your prefix installation:       
           
```

**Comment by ryanvolz** [comment]
I can't say I fully understand how the conflict worked here, but "conflict with pothos" is good enough for me. I guess it was taking preference on the executable path.

Only things that are Python scripts with an exe wrapper go in the Scripts directory, so that looks rather normal to me. Other things can be in Library\bin.
