### ISSUE TITLE
/? Text Mistake

### ISSUE THREAD

**Issue by Calyso** [ryanvolz/radioconda#24]
The text for /NoRegistry (brought up using *.exe /?) lists AllUsers and JustMe both as 0. Found in the 2022.06.24 release and would be considered a cosmetic issue. 

![RoyalTS_7E8ZfUmRFT](https://user-images.githubusercontent.com/6992087/182050799-bfe5596b-d519-4e5a-8166-f12e28d62ec8.png)

**Comment by ryanvolz** [comment]
Thanks for the report. All of that text is inherited from [conda constructor](https://github.com/conda/constructor), so it might take some digging to get it changed. I can look into it though.

**Comment by ryanvolz** [comment]
Oh, I get what this is trying to say now: for either installation type (AllUsers and JustMe), the default for /NoRegistry is 0 (not enabled). So I suppose the text is correct, but it would be clearer just to list "default: 0".
