### ISSUE TITLE
Strange screen resolution and crash on macOS Big Sur

### ISSUE THREAD

**Issue by oryxcam** [ryanvolz/radioconda#3]
Installed, and re-installed radioconda via command line using https://glare.now.sh/ryanvolz/radioconda/radioconda-.*-MacOSX-x86_64.sh.
GnuRadio opens but in a very small scale (1/4 of screen) and then crashes as soon as I try to access the gnuradio menu.

Prompt when starting gnuradio is:

(gnuradio-companion:8991): Gtk-WARNING **: 00:15:35.492: Locale not supported by C library.
	Using the fallback 'C' locale.
No such schema ?org.gnome.desktop.interface?

Thank you

Daniel

[screenshot](https://hb9iiu.com/public_files/2021-08-26_00-16-34.png
)

**Comment by ryanvolz** [comment]
I think I've heard of this being a problem for GNU Radio itself (not just radioconda) with retina displays on macOS (hence the 1/4 screen, it doesn't get scaled properly for the high resolution). Searching the GNU Radio github though, I don't see it as an existing issue, so I probably just heard it through the grapevine. I'm going to suggest posting this issue [over there](https://github.com/gnuradio/gnuradio) to spur upstream to try to fix it.

**Comment by ryanvolz** [comment]
> I am also seeing this using radioconda. Homebrew doesn't have this issue.

That's a useful data point, thanks! Homebrew doesn't appear to have any extra patches for GNU Radio, so I'm wondering what the difference is. Probably something lower in the gtk3 graphics stack. I'll do some more digging.

**Comment by ryanvolz** [comment]
@warnes Can you tell me what version of `pygobject` and `gobject-introspection` the working Homebrew build uses?

**Comment by warnes** [comment]
Here are the package installed in the GnuRadio python virtual environment:

```
(venv)  % . /usr/local/Cellar/gnuradio//3.9.2.0_2/libexec/venv/bin/activate

(venv)  % pip list
Package               Version
--------------------- -------
Cheetah3              3.2.6
click                 8.0.1
click-plugins         1.1.1
Mako                  1.1.4
numpy                 1.21.2
pip                   21.2.4
pycairo               1.20.1
PyGObject             3.40.1
PyQt3D                5.15.4
PyQt5                 5.15.4
PyQt5-sip             12.9.0
PyQtChart             5.15.4
PyQtDataVisualization 5.15.4
PyQtNetworkAuth       5.15.4
PyQtPurchasing        5.15.4
PyQtWebEngine         5.15.4
PyYAML                5.4.1
setuptools            56.0.0
six                   1.16.0
```

**Comment by ryanvolz** [comment]
Just tagging possibly-related issues for tracking:

Non-merged workaround for high DPI displays with macOS: https://github.com/gnuradio/gnuradio/pull/4814
Various issues with GR on arm64 macOS: https://github.com/gnuradio/gnuradio/issues/4420

**Comment by warnes** [comment]
My machine details:

- MacOs 11.6
- 2.6 GHz 6-Core Intel Core i7
- 32 GB RAM
- AMD Radeon Pro 5300M 4 GB / Intel UHD Graphics 630 1536 M
- Screen size: 3584x2240

Results of `conda list` attached.
[conda_list.txt](https://github.com/ryanvolz/radioconda/files/7212155/conda_list.txt)

**Comment by ryanvolz** [comment]
@warnes Check out my proposed fix in https://github.com/gnuradio/gnuradio/pull/4814#issuecomment-925190019.

**Comment by ryanvolz** [comment]
I have patched packages ready to go [here](https://github.com/conda-forge/gnuradio-feedstock/pull/85) and [here](https://github.com/conda-forge/gnuradio-feedstock/pull/86). If I can get confirmation that the change in https://github.com/gnuradio/gnuradio/pull/4814#issuecomment-925190019 works, then I'll merge those PRs and make a new radioconda release to fix this.

**Comment by gte620v** [comment]
https://github.com/conda-forge/gnuradio-feedstock/pull/85/files worked as a fix for me in conda. I just had to reinstall gnuradio 3.8 using conda.  Thanks for the fix, @ryanvolz!

**Comment by fah** [comment]
@ryanvolz 
I manually applied your [patch](https://github.com/conda-forge/gnuradio-feedstock/pull/85/files) to a pure brew installation of gnuradio, which originally caused the resolution problem. Now it works perfectly. Many thanks!

**Comment by ryanvolz** [comment]
Crash possibly fixed by [this update to `cairo`](https://github.com/conda-forge/cairo-feedstock/pull/68)?

**Comment by ryanvolz** [comment]
Any chance https://github.com/gnuradio/gnuradio/pull/6352 fixes this? That's a python-only fix, so you can manually edit the appropriate installed python files to test it.

**Comment by ryanvolz** [comment]
Closing until I hear that this is still an issue.
