### ISSUE TITLE
Can't select menu items with mouse on GRC on M1 Mac with Arm64 build

### ISSUE THREAD

**Issue by techfoamer** [ryanvolz/radioconda#33]
I can pull menus down with the mouse on my M1 Mac with the Arm64 build.  Cannot select menu entries by pointing and clicking.  I can select these using the cursor keys and enter key as the click.

**Comment by ryanvolz** [comment]
This sounds like issues I've heard about before with macOS and GRC. There might already be a bug filed upstream at https://github.com/gnuradio/gnuradio, but if not it would be good to report there as well.

**Comment by ryanvolz** [comment]
Fixed with GNU Radio 3.10.5.0 in the latest release?

**Comment by techfoamer** [comment]
Fixed!
