### ISSUE TITLE
Please include Inspectrum

### ISSUE THREAD

**Issue by mrlweekes** [ryanvolz/radioconda#34]
Inspectrum is a tool for analyzing captured radio signals. Please include this software in your windows radioconda builds.

Thanks,

**Comment by ryanvolz** [comment]
Thanks for the suggestion. Inspectrum is one that I've been wanting to add for a little while, but maybe this will move it up the priority list. I'll see what I can do for the next release.

**Comment by mrlweekes** [comment]
Thank you.

**Comment by ryanvolz** [comment]
Got this one done for today's release!

**Comment by mrlweekes** [comment]
Thank you very much.

 
 
  On Thu, Jan 19, 2023 at 12:51 PM, Ryan ***@***.***> wrote:   


Got this one done for today's release!
