### ISSUE TITLE
Request: Please include gr-lora_sdr in gnuradio

### ISSUE THREAD

**Issue by mrlweekes** [ryanvolz/radioconda#35]
Please include the OOT module, gr-lora_sdr, from https://github.com/tapparelj/gr-lora_sdr .
Thank you.

**Comment by ryanvolz** [comment]
Also on my list, and will almost certainly happen before the next release since it should be straightforward.

**Comment by ryanvolz** [comment]
> Also on my list, and will almost certainly happen before the next release since it should be straightforward.

Took more than "before the next release", but `gnuradio-lora_sdr` is now available on my `ryanvolz` channel. It will be in the next installer release as soon as a couple blocking conda-forge packages are updated.
