### ISSUE TITLE
Crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by jo-rivera** [ryanvolz/radioconda#4]
Installed radioconda via command line using installer https://glare.now.sh/ryanvolz/radioconda/radioconda-.*-Linux-x86_64.sh

gnuradio-companion opens the first time, after closing and re-opening again it crashes

<img width="312" alt="radioconda-gnuradio-crash" src="https://user-images.githubusercontent.com/20389163/134279757-5cb651a0-dd5e-4ed4-a870-656031001ba0.PNG">

**Comment by ryanvolz** [comment]
Thanks for the report! I think this is the same thing we're investigating [here](https://github.com/conda-forge/gnuradio-feedstock/issues/84).

**Comment by dicta** [comment]
Looks like this should be fixed here by 32ebbbced4dfccdc40f57d240b0ab1c978ada059 now that the underlying issue is resolved upstream.

**Comment by ryanvolz** [comment]
Yes, should be fixed now.
