### ISSUE TITLE
Anaconda navigator - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xjugs** [ryanvolz/radioconda#52]
After I installed radioconda, when I try open the anaconda navigator, there is segmetaion error:
Segmentation fault (core dumped)

why?

**Comment by ryanvolz** [comment]
Hmm, I'm not sure why that would happen. Could be that it no longer likes the app entry provided for GNU Radio. Is this on Windows?

**Comment by ryanvolz** [comment]
Is this still an issue? Please re-open if it is.

**Comment by xjugs** [comment]
Thanks!
