### ISSUE TITLE
How to update radioconda

### ISSUE THREAD

**Issue by urima** [ryanvolz/radioconda#54]
How can I update a radioconda that was install using conda:
"conda create -n radioconda -c conda-forge -c ryanvolz --only-deps radioconda"
?
Thnaks.

**Comment by ryanvolz** [comment]
Any of the usual methods will work: https://github.com/ryanvolz/radioconda#upgrade (you can use `conda` instead of `mamba`). The `conda install --file` methods will bypass the conda solver and therefore should be the fastest.
