### ISSUE TITLE
Latest Radioconda package for Windows - GNU Radio companion doesn't work

### ISSUE THREAD

**Issue by luks81** [ryanvolz/radioconda#60]
Good Day

Maybe someone will be able to help.

Latest Radioconda package for windows installed on Windows 10 (64) Intel Pentium CPU 4425Y - GNU radio companion does not work. GNU Radio Companion 3.10.5.1 and Python 3.10.9

1.While executing simple signal generator module and QT GUI waterfall sink module -mgnu radio companiom does nothing and returns 👍

Done (return code 3221225501)

2 While executing Soapy Hack RF source module connecter to Soapy Hack RF sink module - GNU radio companion displays empty window and sets Hack RF TX and RX LEDs simultaneusly until Window is closed.

Because of No1 it seems to be the problem not related to Hack RF itself . Thanks

**Comment by ryanvolz** [comment]
The first problem sounds like #25. I don't have a good fix for that yet, but maybe you can downgrade to an older version of the `fftw` package to get it working.

The HackRF problem I'm less sure about. Is that truly something that used to work with a previous version? Is there anything else in the flowgraph besides source to sink? If not, it sounds like it's running exactly what you asked and an empty window makes sense?

**Comment by luks81** [comment]
Good Day

Thank you for your reply. 

I installed the radioconda packages dated 2021.03.12 and 2021.03.22and GNU radio companion 3.8.2 and Python 3.8 are ok in regards to executing simple generator and and QT GUI waterfall sink module.

The Hack RF porta Pack however is not reckognised by CubicSDR  and GNU Radio Companion using Osmocon Source as well as Soapy Source. In relation to Osmocon the fault looks like below:

__**gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file rtl rtl_tcp uhd soapy
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.1; Boost_107400; UHD_3.15.0.0-release
Traceback (most recent call last):
  File "C:\Users\BVNH\Documents\hji.py", line 233, in <module>
    main()
  File "C:\Users\BVNH\Documents\hji.py", line 209, in main
    tb = top_block_cls()
  File "C:\Users\BVNH\Documents\hji.py", line 153, in __init__
    self.osmosdr_source_0 = osmosdr.source(
  File "C:\Users\BVNH\radioconda\lib\site-packages\osmosdr\osmosdr_swig.py", line 946, in make
    return _osmosdr_swig.source_make(*args, **kwargs)
RuntimeError: No supported devices found (check the connection and/or udev rules).**__

In relation to soapy source:

_Executing: C:\Users\BVNH\radioconda\python.exe -u C:\Users\BVNH\Documents\hji.py

Traceback (most recent call last):
  File "C:\Users\BVNH\Documents\hji.py", line 267, in <module>
    main()
  File "C:\Users\BVNH\Documents\hji.py", line 243, in main
    tb = top_block_cls()
  File "C:\Users\BVNH\Documents\hji.py", line 96, in __init__
    self.soapy_source_0 = soapy.source(1, dev, dev_args, '',
  File "C:\Users\BVNH\radioconda\lib\site-packages\soapy\soapy_swig.py", line 92, in make
    return _soapy_swig.source_make(nchan, device, dev_args, stream_args, tune_args, other_settings, sampling_rate, type)
RuntimeError: SoapySDR::Device::make() no match_


In relation to the usage of the mentioned sources - I don't have any experience and practical experience in how to use them and what the response should be - the intention is just to get the Hack RF device to receive and transmit in GNU Radio companion. It looks that there is link missing how to assign Hack RF porta pack to Osmocom source.

I updated the packages manually using the "power shell" with prompt

conda update --all 

but after updating the response was same as initially return code 3221225501.

Any idea what can be missing ?

**Comment by ryanvolz** [comment]
> I updated the packages manually using the "power shell" with prompt
> 
> conda update --all
> 
> but after updating the response was same as initially return code 3221225501.

At least for now, you're stuck using older, non-upgraded packages if you want to avoid this issue. Others have had luck with manually replacing files from an older `fftw` package: https://github.com/ryanvolz/radioconda/issues/25#issuecomment-1236087035. I'm hopeful that I can come up with a proper fix for this soon.

With those older installers though, I don't think they had HackRF device support yet, so that would explain why they can't find the device. If you don't want to muck around with manually replacing `fftw` files on the latest release, then start with https://github.com/ryanvolz/radioconda/releases/tag/2022.02.01 since that's the first one with HackRF support and I think it avoids this `fftw`  bug.

**Comment by ryanvolz** [comment]
I think I have a fix for `fftw`. If you want to test it, then you can install this [rebuilt package](https://anaconda.org/ryanvolz/fftw/3.3.10/download/win-64/fftw-3.3.10-nompi_h5648b18_107.conda) using the latest release. From a radioconda prompt, you can run
```
mamba install https://anaconda.org/ryanvolz/fftw/3.3.10/download/win-64/fftw-3.3.10-nompi_h5648b18_107.conda
```
Let me know if this fixes things for the Qt GUI Waterfall Sink. Thanks!

**Comment by luks81** [comment]
Good Day

Thank you for your reply and help. 

With using the above prompt there is some error. Please see below the report:

_(base) C:\Users\BVNH>mamba install https://anaconda.org/ryanvolz/fftw/3.3.10/download/win-64/fftw-3.3.10-nompi_h5648b18_107.conda

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.3.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ryanvolz/fftw/3.3.10/download/win-64::fftw==3.3.10=nompi_h5648b18_107']

warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not remove state file "C:\\Users\\BVNH\\radioconda\\pkgs\\cache\\da19b8e8.state.json": Proces nie mo┐e uzyskaŠ dostŕpu do pliku, poniewa┐ jest on u┐ywany przez inny proces.
warning  libmamba Could not parse state file: Could not load cache state: [json.exception.type_error.302] type must be string, but is null
warning  libmamba Could not remove state file "C:\\Users\\BVNH\\radioconda\\pkgs\\cache\\d8f1edbb.state.json": Proces nie mo┐e uzyskaŠ dostŕpu do pliku, poniewa┐ jest on u┐ywany przez inny proces.
https://anaconda.org/ryanvolz/fftw/3.3.10/downlo..   3.3kB @   3.4kB/s 404 failed  1.0s
ryanvolz/noarch                                    849.0 B @ 866.0 B/s  1.0s
ryanvolz/win-64                                     24.1kB @  21.6kB/s  1.1s
https://anaconda.org/ryanvolz/fftw/3.3.10/downlo..   3.3kB @   2.7kB/s 404 failed  0.3s
Multi-download failed. Reason: Transfer finalized, status: 404 [https://anaconda.org/ryanvolz/fftw/3.3.10/download/noarch/repodata.json] 3286 bytes

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\BVNH\radioconda\lib\site-packages\conda\exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\mamba.py", line 936, in exception_converter
        raise e
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\mamba.py", line 887, in _wrapped_main
        result = do_call(parsed_args, p)
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\utils.py", line 129, in load_channels
        index = get_index(
      File "C:\Users\BVNH\radioconda\lib\site-packages\mamba\utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://anaconda.org/ryanvolz/fftw/3.3.10/download/noarch/repodata.json] 3286 bytes

`$ C:\Users\BVNH\radioconda\Scripts\mamba install https://anaconda.org/ryanvolz/fftw/3.3.10/download/win-64/fftw-3.3.10-nompi_h5648b18_107.conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\BVNH\radioconda\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\BVNH\radioconda\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\BVNH\radioconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\BVNH\radioconda\python.exe
               CONDA_ROOT=C:\Users\BVNH\radioconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\BVNH
               LD_PRELOAD=<not set>
                     PATH=C:\Users\BVNH\radioconda;C:\Users\BVNH\radioconda\Library\mingw-
                          w64\bin;C:\Users\BVNH\radioconda\Library\usr\bin;C:\Users\BVNH\radioco
                          nda\Library\bin;C:\Users\BVNH\radioconda\Scripts;C:\Users\BVNH\radioco
                          nda\bin;C:\Users\BVNH\radioconda\condabin;C:\WINDOWS\system32;C:\WINDO
                          WS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0
                          ;C:\WINDOWS\System32\OpenSSH;C:\Program Files\MATLAB\MATLAB Production
                          Server\R2015a\runtime\win64;C:\Program Files\MATLAB\MATLAB Production
                          Server\R2015a\bin;C:\Program Files\MATLAB\MATLAB Production Server\R20
                          15a\polyspace\bin;C:\Users\BVNH\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\BVNH\radioconda
            shell level : 1
       user config file : C:\Users\BVNH\.condarc
 populated config files : C:\Users\BVNH\radioconda\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\BVNH\radioconda  (writable)
      conda av data dir : C:\Users\BVNH\radioconda\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ryanvolz/win-64
                          https://conda.anaconda.org/ryanvolz/noarch
          package cache : C:\Users\BVNH\radioconda\pkgs
                          C:\Users\BVNH\.conda\pkgs
                          C:\Users\BVNH\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\BVNH\radioconda\envs
                          C:\Users\BVNH\.conda\envs
                          C:\Users\BVNH\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.9 Windows/10 Windows/10.0.18363
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report._

I managed to clear the fault by manually replacing fftw3.dll and fftw3f.dll(from old radioconda release) within the latest radioconda release installation- same idea like in #25 issue.

In addition , when previously tried to install hackrf package onto old radioconda release or update the old radioconda release package  using  the prompt 

_Conda update --all_ 

the fftw-3.3.10 was part of the package installed and the result was poor - same issues as with new release.

At the moment I can use the GNU radio companion butI will be more than happy to help with solving the code 3221225501 problem

**Comment by ryanvolz** [comment]
Alright, mamba doesn't like installing the file directly. But you can now upgrade to the latest `fftw` with the fix just with `mamba upgrade --all` or `conda upgrade --all`. I'm fairly sure that will take care of the code 3221225501 problem. New installer release coming soon.

So where does that leave things with Hack RF? Is there still an issue there with the latest packages?

**Comment by luks81** [comment]
Hi

Thanks for help. After updating all, the problem is gone. GNU Radio companion is operational - to the extend of my current knowledge. 

There is small problem with Soapy Hack RF source - as it sets RX LED "on" on the unit when tuned to receive the FM band frequencies between 94-98 MHz- but does not receive any peaks on Frequency sink. When Osmocon source is used, the unit peaks 4-5 different signals. This however may come from the lack of idea of how the Soapy Hack RF Source should work or how be tuned. I will investigate and write the status.

Regards
