### ISSUE TITLE
gnuradio-adsb OOT won't install

### ISSUE THREAD

**Issue by mebrown47** [ryanvolz/radioconda#62]
New to RadioConda so this might be a learning issue.  Gnuradio 3.10 works fine in the default radioconda env and successfully installed gnuradio-iridium OOT however gnuradio-adsb won't install -- it reports a Python >= 3.9 error even tho v 3.10 is installed. So my question is if the python dependency is satisfied where is the OOT failing and is there a more granular error reporting (log file?) when adding to the base radioconda?  Thanks

**Comment by ryanvolz** [comment]
I'd forgotten I'd ever made a package for `gnuradio-adsb`! Of course, that means I haven't updated it, so it certainly needs to be rebuilt to work with the latest radioconda. I'll do that and plan on including it in the next release, which should be soon.

**Comment by mebrown47** [comment]
Thanks!
