### ISSUE TITLE
Copying text cause crash

### ISSUE THREAD

**Issue by fkvd** [ryanvolz/radioconda#65]
Hi, I am using the latest version of radioconda in windows. All blocks and functions work perfectly. However, the program crash when I right click and copy the text in terminal or a block parameter. Is it just me or is there anyone who has the same problem?

Version: 3.10.6.0 (Python 3.10.10)

**Comment by ryanvolz** [comment]
Hmm, not exactly the same result (not crashing) but still someone reporting issues with the clipboard on Windows: https://github.com/conda-forge/gnuradio-feedstock/issues/111

So far I haven't been able to reproduce these issues. Is there anything notable about your system as it relates to the clipboard? What version of Windows are you using, in case it matters?

**Comment by fkvd** [comment]
I am using 22H2 version of windows 10 and my clipboard history setting is on (I don't know whether it is important or not). I also realized that (sometimes) even right click in terminal screen causes to crash.

**Comment by ryanvolz** [comment]
> I also realized that (sometimes) even right click in terminal screen causes to crash.

Is that the terminal within the GNU Radio Companion window? 🤔

**Comment by fkvd** [comment]
> > I also realized that (sometimes) even right click in terminal screen causes to crash.
> 
> Is that the terminal within the GNU Radio Companion window? 🤔

Sorry for confusion, yes I am talking about the terminal in GNU Radio or simply "console panel".

**Comment by rogerwim** [comment]
i can confirm this, am on windows 11, though I also have random craches sometimes

**Comment by ryanvolz** [comment]
Thanks for the details everyone! GTK overall and/or the terminal window within GRC does seem to be pretty buggy on Windows. It remains to be seen whether that is a bug in the packaging with radioconda/conda-forge or if this is a universal GRC on Windows thing. Now that I can reproduce it, I'll attempt some A/B testing to try to narrow down what's happening.
