### ISSUE TITLE
Radioconda not available for download and message in the browser

### ISSUE THREAD

**Issue by PedroA-Vieira** [ryanvolz/radioconda#68]
When clicking on the link to download Radioconda for Windows, the message below appears in the browser. What can it be? Has anyone had this problem? any way to resolve?

URL: https://glare.vercel.app/ryanvolz/radioconda/radioconda-.*-Windows-x86_64.exe
Message in browser:

{"github_api_msg":{"documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting","message":"API rate limit exceeded for 52.53.230.231. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"},"message":"error from GitHub API"}

**Comment by ryanvolz** [comment]
Thanks for the report! I had to change the links to avoid the API rate limit, and the new links should be working now. For Windows, you will want https://glare-sable.vercel.app/ryanvolz/radioconda/radioconda-.*-Windows-x86_64.exe.

For future reference if this crops up again, it is always possible to navigate to the [latest release on GitHub](https://github.com/ryanvolz/radioconda/releases/latest) and download the platform-specific installer from there.
