### ISSUE TITLE
Device Control -> RFNoC Graph (Device) is not available and causes exceptions

### ISSUE THREAD

**Issue by yourarchipelago** [ryanvolz/radioconda#69]
Here is the log:
![log](https://github.com/ryanvolz/radioconda/assets/35392794/3943501a-a0ac-469f-ba3b-8076654e5e88)

**Comment by ryanvolz** [comment]
Perhaps something fixed by https://github.com/gnuradio/gnuradio/pull/6602, which is in the new GR 3.10.7.0 and should appear in radioconda soon (currently rebuilding OOT modules)?

**Comment by yourarchipelago** [comment]
Thanks, I get it. 
The issue of C++ OOT modules remains unsolved, I cannot find anything that I can do to fix it.
