### ISSUE TITLE
After fresh installation, there's a $PREFIX/lib/python3.1 directory

### ISSUE THREAD

**Issue by marcusmueller** [ryanvolz/radioconda#72]
Don't think there even was a Python 3.1 that ever saw significant publicity, so I wonder what that directory does! (It's but a symlink to python3.10)

**Comment by marcusmueller** [comment]
Oh, after figuring out `conda package --which`, this seems to be an upstream python-3.10.12 packaging issue. huh!

**Comment by ryanvolz** [comment]
I believe it's a purposeful symlink, because some things always expected a two-digit 'x.y' Python version number.
