### ISSUE TITLE
issue with UDP-SINK

### ISSUE THREAD

**Issue by Lunny1993** [ryanvolz/radioconda#82]
1、My gnuradio by radioconda on windows version：
![微信截图_20231214114109](https://github.com/ryanvolz/radioconda/assets/45454215/4be65021-5f60-49fa-8a11-708f4af53e0a)
2、My flowgraph to get and send spectrum data over UDP-SINK：
![微信截图_20231214115002](https://github.com/ryanvolz/radioconda/assets/45454215/ac514726-2b00-43a5-bfff-32d9cc6cb5da)
![微信截图_20231214115049](https://github.com/ryanvolz/radioconda/assets/45454215/8ebfaf7c-d761-49ca-a318-11bd3b1689e8)
3、In fact, after the flowgraph runs, only a few packets of UDP data can be sent, and then the UDP packets stop sending.
![微信截图_20231214115513](https://github.com/ryanvolz/radioconda/assets/45454215/fdedf2c7-d52d-468f-9b65-729cc40f753c)
4、I tried lowering the sample rate or lowering the FFT size etc, but it still didn't work.
5、I noticed the "NOTE" for "UDP-SINK", but how to add the following lines to "/etc/sysctl.conf" on the windows version?
![image](https://github.com/ryanvolz/radioconda/assets/45454215/13a861ac-7083-4eda-abc8-c63ab2f62e35)

Can anyone fix it? Ask for advice! Thanks a lot!

**Comment by ryanvolz** [comment]
Hi @Lunny1993! I was going to suggest that you post this over at https://github.com/gnuradio/gnuradio where far more eyes would see it and be able to help, but I see you've already done that! I personally have little experience with the UDP Sink, but I would be suspicious of the high packet data size you're trying to use. If you have jumbo frames enabled (and I have no idea how to do this on Windows) then your packet size works, but it doesn't for standard frames. Do you get better results if you change the packet data size back down to the default of 1472? I know that doesn't fit a whole FFT, which I assume is your intention by setting it to `fft_size * 4` where the `4` comes from the 4 bytes per float32 sample.

You might also to well to look into the "ZMQ PUB Sink" or "ZMQ PUSH Sink" as alternatives for sending packetized data to another application. That only works if you can use ZeroMQ on the other end though.

**Comment by yourarchipelago** [comment]
I found this issue last year.

**Comment by ryanvolz** [comment]
Probably best handled upstream at the GNU Radio issue tracker on GitHub if there are still issues with the UDP Sink on Windows.
