### ISSUE TITLE
Cannot enter decimals in Filter Design Tool

### ISSUE THREAD

**Issue by pakluba** [ryanvolz/radioconda#83]
At least in the Hungarian locale a decimal comma is in use instead of a decimal dot. When designing IIR filters, the "End of Pass Band" has an initial value of "0.3" which is wrong as it should show "0,3" (but this is not a big issue just related). The "Start of Stop Band" is set to "0.5". And the problem is that it's impossible to change these values because a decimal dot cannot be entered at all. A decimal comma can be entered but due to some incorrect validation logic the value is not accepted and the filter is not recalculated after pressing the "Design" button.

**Comment by ryanvolz** [comment]
There is an issue upstream for this: https://github.com/gnuradio/gnuradio/issues/5130.
