### ISSUE TITLE
Spyder IDE

### ISSUE THREAD

**Issue by urima** [ryanvolz/radioconda#84]
Hello,

Please add spyder IDE to radioconda package.
If it is too heavy, please consider to add spyker-kernels.

The problem is that even if I use the spyder from anaconda and choose the intepeter as radioconda python the console says there is no spyder-kernels.

Thanks,
Uri

**Comment by ryanvolz** [comment]
It's probably a bit heavy to add `spyder` for everyone, but post-installation should be straightforward. What you need to do is [activate your radioconda environment in a console](https://github.com/ryanvolz/radioconda?tab=readme-ov-file#use) and run `mamba install spyder-kernels`. Alternatively, you can install spyder directly into that environment and run it from there with `mamba install spyder`, so you wouldn't need a separate installation from Anaconda.
