### ISSUE TITLE
gqrx doesn't launch from menu shortcut on Windows (shortcut is broken in 2024.01.26 release)

### ISSUE THREAD

**Issue by TIT8** [ryanvolz/radioconda#89]
Helllo folks, I have a stupid question.

I've just installed the radioconta latest version on WIndows 11 and it correctly install Gnu Radio Companion on the Start Menu that works very well.
But with GRC, it install also gqrx which doesn't work (if I click on it, it opens a terminal that after a second is closed and nothing appear anymore). 

I noticed that the version carried by radioconda is the **2.17.3**, while the latest one (**2.17.4**) is the first to have Windows binary. So I did a `mamba upgrade --all` and it install correctly the latest version, but clicking on the gqrx app on the start menu still doesn't work.

Finally I installed gqrx from the [official repo](https://github.com/gqrx-sdr/gqrx/releases/tag/v2.17.4) and it works pretty well (only with RTL-SDR for now). 

Am I missing something? Thanks in advance.

**Comment by ryanvolz** [comment]
What happens when you run gqrx from the Conda prompt? Does the terminal output give any clues for why it doesn't load?

If I had to take a guess right now without more information, you're probably running into an issue with the Qt libraries that gqrx uses. The discussion at #78 would be relevant in that case. Quick takeaway: if you have PothosSDR install, uninstalling that might fix this.

**Comment by TIT8** [comment]
I don't have PothosSDR.

Running gqrx from the Conda prompt it works well. Sorry I didn't think about that solution. 
But then, why from the shortcut it doesn't work?

**Comment by ryanvolz** [comment]
If it works from the Conda prompt, then it's not a Qt library thing that is the issue. I don't know why launching from the prompt would be different than using the Start Menu shortcut, but clearly there is something. I'll have to see if I can reproduce.

**Comment by ryanvolz** [comment]
Got some time finally and tracked this down to the menu shortcut being totally wrong on account of a big change in how conda creates menu items. I'm updating the gqrx package to the new menu format which should fix the problem. That updated package will be in the next release, at which time I'll close this.

**Comment by ryanvolz** [comment]
Fixed in 2024.05.29 release.
