### ISSUE TITLE
Source code of the Signal Generatoe FMCW Out of the tree block.

### ISSUE THREAD

**Issue by patilraj1707** [ryanvolz/radioconda#90]
I was trying to implement a FMCW radar in gnu radio using pluto SDR by making my own block but then I came to know that there exists an block in windows that gives you the chirp signal, so it would be very helpfull if you would be able to provide me the yaml and the python files or atlest tell me the location of the files in my installation.

![image](https://github.com/ryanvolz/radioconda/assets/81311326/a9d58c7f-1adb-4006-b064-73c8631dc214)

**Comment by ryanvolz** [comment]
That block is part of the gr-radar OOT module, and the source code is on GitHub at https://github.com/kit-cel/gr-radar/blob/master/lib/signal_generator_fmcw_c_impl.cc. It's not a Python block, but C++. The GRC YAML file is here https://github.com/kit-cel/gr-radar/blob/master/grc/radar_signal_generator_fmcw_c.block.yml.

**Comment by patilraj1707** [comment]
Can you share a example imolementation of this block because some parameters of the block are confusing to me.

**Comment by ryanvolz** [comment]
Sorry, I didn't write the block not have I ever used it, so I don't know anything more than what I've already linked. Looking at the code, it appears that the block outputs 3 blocks of samples of specified lengths before repeating:

1. `Samples CW` samples of CW at the specified `Frequency CW`
2. `Samples up-chirp` samples of of the signal linearly increasing in frequency starting at `Frequency CW`  and ending at `Frequency CW` + `Sweep frequency`
3. `Samples down-chirp` samples of of the signal linearly decreasing in frequency starting at `Frequency CW` + `Sweep frequency` and ending at `Frequency CW`

**Comment by patilraj1707** [comment]
okay thank you very much
