### ISSUE TITLE
Filter Design Tool produces error:  Module 'scipy' has no attribute 'complex128'

### ISSUE THREAD

**Issue by anastas** [ryanvolz/radioconda#91]
On Windows 10, the latest gnuradio 3.10.9.2 produces the above error when you press the "Design" button.

I verified that in the installed python 3.11.7, 
scipy does not have such a type "complex128".
I also verified that numpy does have such type.

**Comment by jwkunz** [comment]
I can verify this inside my arch linux install.  I also submitted a version of this bug report the gnuradio repository for 3.10.9.2.  i haven't checked if 3.11 or 4.0 fix it.

**Comment by ryanvolz** [comment]
Thanks for the reports! This has been fixed upstream following the bug report there with https://github.com/gnuradio/gnuradio/pull/7230, so it will follow into radioconda with the next GNU Radio release (soon).
